server:
  port: 10001
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: world
  profiles:
    active: @profiles.active@
  # jackson全局时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 缓存管理器
  cache:
    type: redis
    redis:
      # 是否存入空值，防止击穿
      cache-null-values: true
      # 使用前缀，分区
      use-key-prefix: true

# MyBatisFlex配置
mybatis-flex:
  # 配置扫描路径
  mapper-package: com.world.**.mapper
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.world.**.mapper
  # 对应的 XML 文件位置
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    key-config:
      key-type: auto
    logic-delete-column: delFlag
    # 逻辑未删除值
    normal-value-of-logic-delete: 0
    # 逻辑已删除值
    deleted-value-of-logic-delete: 1
